name = "Archit Gupta"
rol = "Aspiring Sofware Developer"
email = "i.architgupta07@gmail.com"
phone = "+91-7267845678"
birthday = "February 07, 2003"
location = "India"
avatar = "./config/assets/avatars/pfp_archit.jpg"
username = "i-archit-gupta" # <-- github user name
googlemaps = "https://maps.app.goo.gl/maFEECudqMqEmffy9" 
presentation = """
With hands-on experience in data science and cloud technologies. I’ve developed NLP applications and optimized sentiment analysis models during internships. Proficient in Python, TensorFlow, and AWS, I excel at transforming complex data into actionable insights. I thrive on attending events and conferences to network and build connections. Let’s connect and explore how we can innovate together!
"""
