[[doing]]
title = "Machine Learning"
icon = "./config/assets/icons/ai.svg"
text = "Exploring machine learning and turning data into cool insights! Just having fun with algorithms and making AI magic happen."

[[doing]]
title = "Scripting"
icon = "./config/assets/icons/code.svg"
text = "Automation and task scripting using Python to enhance efficiency and productivity."

[[doing]]
title = "Cloud Computing"
icon = "./config/assets/icons/firebase.svg"
text = "Exploring the cloud and its services to deploy applications and services."

[[doing]]
title = "Cybersecurity"
icon = "./config/assets/icons/linux.svg"   
text = "Learning about cybersecurity and ethical hacking to secure applications and networks."
