[[project]]
title = "SummarizeME"
category = "Python"
image = "https://imgur.com/kyHrBGk.png"
url = "https://github.com/i-archit-gupta/SummarizeME"

[[project]]
title = "Fruit Ninja CV"
category = "Machine Learning"
image = "https://i.imgur.com/OhJcybHb.jpg"
url = "https://github.com/i-archit-gupta/FruitNinjaCV"
