############## Education config #################
#################################################
[[education]]
title = "CBSE Class 10 Boards(AISSE)"
timeline = "2008 - 2018"
description = "Studied at Delhi Public School Azaad Nagar, Kanpur, India with an aggregate of 91.2%"

[[education]]
title = "CBSE Class 12 Boards(AISSCE)"
timeline = "2018 - 2020"
description = "Studied at Delhi Public School Azaad Nagar, Kanpur, India with an aggregate of 87%"

[[education]]
title = "B.Tech in Computer Science and Engineering"
timeline = "2021 - 2025"
description = "Currently studying at Kalinga Institute of Industrial Technology, Bhubaneswar with a CGPA of 8.97"


############## Experience config ################
#################################################
[[experience]]
title = "Data Science Intern at Zep Analytics"
timeline = "June 2024 - July 2024"
description = "Chat Scholar Project: Developed a PDF chat application and essay grading system using NLP techniques."

[[experience]]
title = "CTDP Trainee at PwC India"
timeline = "May 2024 - June 2024"
description = "Acquired hands-on experience with AWS services, including RDS, EC2, and S3"

############## Skills config ####################
#################################################
[skills] 
title = "My Skills"
enabled = true
show_bar = true
show_value = true

[[skill]]
title = "C/C++"
value = "80%"

[[skill]]
title = "Python"
value = "90%"

[[skill]]
title = "MYSQL"
value = "85%"

[[skill]]
title = "Bash"
value = "70%"

############## Language config ##################
#################################################
[languages]
title = "Languages"
enabled = true
show_bar = true
show_value = true

[[language]]
title = "Hindi"
value = "100%"

[[language]]
title = "English"
value = "90%"

[[language]]
title = "German"
value = "40%"
