# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://iarchitgupta.com/"

logo-facebook = "https://www.facebook.com/archit.gupta.7731/"
logo-twitter = "https://twitter.com/iarchitX"
logo-instagram = "https://www.instagram.com/i.architgupta"
logo-linkedin = "https://www.linkedin.com/in/archit-gupta-339499198/"
logo-github = "https://github.com/i-archit-gupta/"
